### ISSUE TITLE
HikariCP 관련 오류

### ISSUE THREAD

**Issue by endless87** [darkness87/AMISystem#33]
HikariCP - Pool stats (total=50, active=28, idle=22, waiting=0)

active가 max pool 사이즈로 되었을 경우 DB커넥션 오류 발생

현재 복구방법 : 앱 재기동
재기동 없이 복구 가능 방법 필요 및 미필요 커넥션에 대하여 처리 필요

![image.png](https://images.zenhubusercontent.com/5f27b089a9416e6cd5a2ba78/c0f5efdb-124b-45dc-9ee2-80ea5b522801)

**Comment by endless87** [comment]
특정 커넥션이 종료가 안되고 active 상태로 동작 하는 문제로 추측

21-05-06 11:08:05.432 DEBUG 147278973 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.logPoolState:421 : HikariCP - Pool stats (total=50, active=31, idle=19, waiting=0)
21-05-06 11:08:05.433 DEBUG 147278974 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.fillPool:517 : HikariCP - Fill pool skipped, pool is at sufficient level.

SQL
SHOW FULL PROCESSLIST;
SHOW STATUS LIKE 'Threads_connected';
SHOW STATUS LIKE 'Threads_running';

![image](https://user-images.githubusercontent.com/45387912/117232155-94678000-ae5b-11eb-95e6-24061a7df1c1.png)

![image](https://user-images.githubusercontent.com/45387912/117232196-a21d0580-ae5b-11eb-8926-da930ef98c26.png)

**Comment by endless87** [comment]
현황판에서의 오류사항으로 보임 - Flux 관련 내용 확인 필요


21-05-06 11:29:39.447 DEBUG 64994 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.logPoolState:421 : HikariCP - Pool stats (total=50, active=1, idle=49, waiting=0)
21-05-06 11:29:39.448 DEBUG 64995 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.fillPool:517 : HikariCP - Fill pool skipped, pool is at sufficient level.
21-05-06 11:29:47.884 INFO  73431 - [ parallel-1 ] reactor.Flux.Map.1.info:274 : onNext(com.cnu.ami.common.ResponseListVO@45f7d4f9)
21-05-06 11:29:47.892 INFO  73439 - [ task-7 ] reactor.Flux.Map.1.info:274 : request(1)
21-05-06 11:29:49.087 INFO  74634 - [ parallel-2 ] reactor.Flux.Map.2.info:274 : onNext(com.cnu.ami.common.ResponseArrayVO@399f1fa7)
21-05-06 11:29:49.092 INFO  74639 - [ task-1 ] reactor.Flux.Map.2.info:274 : request(1)
21-05-06 11:29:55.640 INFO  81187 - [ ajp-nio-127.0.0.1-19099-exec-6 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:118 : Token Userid : user003
21-05-06 11:29:55.640 INFO  81187 - [ ajp-nio-127.0.0.1-19099-exec-5 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:118 : Token Userid : user003
21-05-06 11:29:55.644 INFO  81191 - [ ajp-nio-127.0.0.1-19099-exec-6 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:122 : userLoginVO : com.cnu.ami.login.dao.entity.UserLoginVO@265e3ed4
21-05-06 11:29:55.644 INFO  81191 - [ ajp-nio-127.0.0.1-19099-exec-5 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:122 : userLoginVO : com.cnu.ami.login.dao.entity.UserLoginVO@6ec3f02f
21-05-06 11:29:55.647 INFO  81194 - [ ajp-nio-127.0.0.1-19099-exec-5 ] reactor.Flux.Map.3.info:274 : onSubscribe(FluxMap.MapSubscriber)
21-05-06 11:29:55.648 INFO  81195 - [ ajp-nio-127.0.0.1-19099-exec-5 ] reactor.Flux.Map.3.info:274 : request(1)
21-05-06 11:29:55.683 INFO  81230 - [ ajp-nio-127.0.0.1-19099-exec-7 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:118 : Token Userid : user003
21-05-06 11:29:55.683 INFO  81230 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:118 : Token Userid : user003
21-05-06 11:29:55.686 INFO  81233 - [ ajp-nio-127.0.0.1-19099-exec-7 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:122 : userLoginVO : com.cnu.ami.login.dao.entity.UserLoginVO@6222ab78
21-05-06 11:29:55.686 INFO  81233 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:122 : userLoginVO : com.cnu.ami.login.dao.entity.UserLoginVO@311c5fbc
21-05-06 11:29:55.688 INFO  81235 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.d.s.i.DashBoardServiceImpl.getElectricUseDayHourAll:93 : 20210506,20210505
21-05-06 11:29:55.689 INFO  81236 - [ ajp-nio-127.0.0.1-19099-exec-7 ] c.c.a.d.s.i.DashBoardServiceImpl.getElectricUseDayHourAll:93 : 20210506,20210505
21-05-06 11:29:56.496 INFO  82043 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.d.s.i.DashBoardServiceImpl.getElectricMeterReadingRateDayAll:190 : 20210506,20210505
21-05-06 11:29:56.498 INFO  82045 - [ ajp-nio-127.0.0.1-19099-exec-7 ] c.c.a.d.s.i.DashBoardServiceImpl.getElectricMeterReadingRateDayAll:190 : 20210506,20210505
21-05-06 11:29:56.665 INFO  82212 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.d.s.i.DashBoardServiceImpl.getWeatherRealtimeAll:286 : 1
21-05-06 11:29:56.666 INFO  82213 - [ ajp-nio-127.0.0.1-19099-exec-7 ] c.c.a.d.s.i.DashBoardServiceImpl.getWeatherRealtimeAll:286 : 1
21-05-06 11:29:56.687 INFO  82234 - [ ajp-nio-127.0.0.1-19099-exec-7 ] reactor.Flux.Map.4.info:274 : onSubscribe(FluxMap.MapSubscriber)
21-05-06 11:29:56.687 INFO  82234 - [ ajp-nio-127.0.0.1-19099-exec-7 ] reactor.Flux.Map.4.info:274 : request(1)
21-05-06 11:29:56.693 INFO  82240 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:118 : Token Userid : user003
21-05-06 11:29:56.697 INFO  82244 - [ ajp-nio-127.0.0.1-19099-exec-8 ] c.c.a.l.s.i.LoginServiceImpl.getTokenUserid:122 : userLoginVO : com.cnu.ami.login.dao.entity.UserLoginVO@2222cd4c
21-05-06 11:29:59.666 WARN  85213 - [ HikariCP housekeeper ] c.z.h.p.ProxyLeakTask.run:84 : Connection leak detection triggered for com.mysql.cj.jdbc.ConnectionImpl@4fa1c212 on thread ajp-nio-127.0.0.1-19099-exec-7, stack trace follows
java.lang.Exception: Apparent connection leak detected
        at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
        at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
        at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:108)
        at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:138)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.connection(StatementPreparerImpl.java:50)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$5.doPrepare(StatementPreparerImpl.java:149)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl$StatementPreparationTemplate.prepareStatement(StatementPreparerImpl.java:176)
        at org.hibernate.engine.jdbc.internal.StatementPreparerImpl.prepareQueryStatement(StatementPreparerImpl.java:151)
        at org.hibernate.loader.Loader.prepareQueryStatement(Loader.java:2103)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2040)
        at org.hibernate.loader.Loader.executeQueryStatement(Loader.java:2018)
        at org.hibernate.loader.Loader.doQuery(Loader.java:948)
        at org.hibernate.loader.Loader.doQueryAndInitializeNonLazyCollections(Loader.java:349)
        at org.hibernate.loader.Loader.doList(Loader.java:2849)
        at org.hibernate.loader.Loader.doList(Loader.java:2831)
        at org.hibernate.loader.Loader.listIgnoreQueryCache(Loader.java:2663)
        at org.hibernate.loader.Loader.list(Loader.java:2658)
        at org.hibernate.loader.hql.QueryLoader.list(QueryLoader.java:506)
        at org.hibernate.hql.internal.ast.QueryTranslatorImpl.list(QueryTranslatorImpl.java:400)
        at org.hibernate.engine.query.spi.HQLQueryPlan.performList(HQLQueryPlan.java:219)
        at org.hibernate.internal.SessionImpl.list(SessionImpl.java:1414)
        at org.hibernate.query.internal.AbstractProducedQuery.doList(AbstractProducedQuery.java:1625)
        at org.hibernate.query.internal.AbstractProducedQuery.list(AbstractProducedQuery.java:1593)
        at org.hibernate.query.internal.AbstractProducedQuery.getSingleResult(AbstractProducedQuery.java:1641)
        at org.hibernate.query.criteria.internal.compile.CriteriaQueryTypeQueryAdapter.getSingleResult(CriteriaQueryTypeQueryAdapter.java:111)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution$SingleEntityExecution.doExecute(JpaQueryExecution.java:196)
        at org.springframework.data.jpa.repository.query.JpaQueryExecution.execute(JpaQueryExecution.java:88)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.doExecute(AbstractJpaQuery.java:154)
        at org.springframework.data.jpa.repository.query.AbstractJpaQuery.execute(AbstractJpaQuery.java:142)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor$QueryMethodInvoker.invoke(QueryExecutorMethodInterceptor.java:195)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:152)
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:130)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:80)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:367)
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:149)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
        at com.sun.proxy.$Proxy121.findBySSEQ(Unknown Source)
        at com.cnu.ami.dashboard.service.impl.DashBoardServiceImpl.getWeatherRealtimeAll(DashBoardServiceImpl.java:284)
        at com.cnu.ami.dashboard.controller.DashBoardController.getDashBoardAllData(DashBoardController.java:250)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:878)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:792)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:320)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.invoke(FilterSecurityInterceptor.java:126)
        at org.springframework.security.web.access.intercept.FilterSecurityInterceptor.doFilter(FilterSecurityInterceptor.java:90)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.access.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:118)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.session.SessionManagementFilter.doFilter(SessionManagementFilter.java:137)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.AnonymousAuthenticationFilter.doFilter(AnonymousAuthenticationFilter.java:111)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter.doFilter(SecurityContextHolderAwareRequestFilter.java:158)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.savedrequest.RequestCacheAwareFilter.doFilter(RequestCacheAwareFilter.java:63)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at com.cnu.ami.security.JwtAuthenticationFilter.doFilter(JwtAuthenticationFilter.java:41)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.header.HeaderWriterFilter.doHeadersAfter(HeaderWriterFilter.java:92)
        at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:77)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:542)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:357)
        at org.apache.coyote.ajp.AjpProcessor.service(AjpProcessor.java:433)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:893)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1707)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)
21-05-06 11:30:09.448 DEBUG 94995 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.logPoolState:421 : HikariCP - Pool stats (total=50, active=2, idle=48, waiting=0)
21-05-06 11:30:09.449 DEBUG 94996 - [ HikariCP housekeeper ] c.z.h.p.HikariPool.fillPool:517 : HikariCP - Fill pool skipped, pool is at sufficient level.

**Comment by endless87** [comment]
Flux 사용시 Api DB 여러개 접속후 leak 발생 문제
leak 발생 후 지속 적인 active 상태로 maxPool 크기 까지 증가하면 API 호출을 할 수 없었음

Controller 관련 수정하여 테스트 완료 함 - 당분간 확인을 위하여 로그 기록 진행
